version: '3'
services:
  ad-tpl-vue: #项目的service name
    container_name: 'webhtml' #容器名称
    image: jenkins/jenkins
    restart: always
    ports:
      - 10000:10000
    volumes:
      #~ ./nginx.conf为宿主机目录, /etc/nginx为容器目录
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
      #~ ./dist 为宿主机 build 后的dist目录, /usr/src/app为容器目录,
      - ./dist:/usr/share/nginx/html/ #挂载项目
    privileged: true