version: '3'
services:
  ad-tpl-vue: #项目name
    container_name: 'webhtml' #容器名称
    image: nginx
    restart: always
    ports:
      - 10000:10000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
      - ./dist:/usr/share/nginx/html/ #挂载项目
    privileged: true