version: '3'

services:
  backend:
    build: ./backend
    image: chengheai/backend:latest
    ports:
      - 30000:30000
    links:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_NAME=demo
  frontend:
    build: ./frontend
    image: chengheai/frontend:latest
    links:
      - backend
    ports:
      - "20000:20000"
      - "443:443"
  mongo:
    image: mongo:3.4.9
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

